server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/topic_mgmt?autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false


