package test.p;

public class PrintMystring {
//    private static String s= "Select payroll_salary_process.employee_master_pk "
//            +"\n"+  "	from payroll_salary_process "
//            +"\n"+  "	where payroll_salary_process.current_year= ${current_year} "
//            +"\n"+  "	And payroll_salary_process.current_month= #{current_month} "
//            +"\n"+  "	AND payroll_salary_process.employee_master_pk = ${employee_master_pk} ";

//    private static String s= "SELECT\n"
//            + "	inve_advance_vendor_payment.pk,\n"
//            + " inve_advance_vendor_payment.inve_purchase_committee_pk, "
//            + "	inve_advance_vendor_payment.adv_ref_no,\n"
//            + "	DATE_FORMAT( inve_advance_vendor_payment.created_date, '%d-%m-%Y' ) AS advDate,\n"
//            + "	DATE_FORMAT( inve_advance_vendor_payment.created_date, '%Y-%m-%d' ) AS advDatePrecise,\n"
//            + "	CONCAT(\n"
//            + "		inve_advance_vendor_payment.adv_ref_no,\n"
//            + "		' | ',\n"
//            + "	DATE_FORMAT( inve_advance_vendor_payment.created_date, '%d-%m-%Y' )) AS advTempRefNoDate,\n"
//            + "	CONCAT(\n"
//            + "		inve_advance_vendor_payment.adv_ref_no,\n"
//            + "		' | ',\n"
//            + "	DATE_FORMAT( inve_advance_vendor_payment.approval_date, '%d-%m-%Y' )) AS advFinalRefNoDate,\n"
//            + "	inve_purchase_committee.purchase_committee_no,\n"
//            + "	DATE_FORMAT( inve_purchase_committee.approval_date, '%d-%m-%Y' ) AS pfcDate,\n"
//            + "	CONCAT(\n"
//            + "		inve_purchase_committee.purchase_committee_no,\n"
//            + "		' | ',\n"
//            + "	DATE_FORMAT( inve_purchase_committee.approval_date, '%d-%m-%Y' )) AS pfcNoDate,\n"
//            + "	inve_purchase_committee.pfc_amount AS pfcAmount,\n"
//            + "	department_master.department_name,\n"
//            + "	vendor_master.vendor_name AS vendorName,\n"
//            + "	finance_book_entity.bookEntityCode,\n"
//            + " inve_purchase_committee.pfc_type, "
//            + "	CONCAT(\n"
//            + "		concat(\n"
//            + "			employee_master.first_name,\n"
//            + "			' ',\n"
//            + "		IF\n"
//            + "			( employee_master.middle_name = '', employee_master.last_name, concat( employee_master.middle_name, ' ', employee_master.last_name ) ) \n"
//            + "		), ' ( ' , employee_master.pf_number , ' ) ' ) AS buyerName,\n"
//            + "		inve_advance_vendor_payment.invoice_no as invoiceNo,\n"
//            + "		DATE_FORMAT(inve_advance_vendor_payment.invoice_no,'%d-%m-%Y') as invoiceDate,\n"
//            + "		CONCAT(inve_advance_vendor_payment.invoice_no,' | ',DATE_FORMAT(inve_advance_vendor_payment.invoice_date,'%d-%m-%Y')) as invoiceNoDate,\n"
//            + "	inve_advance_vendor_payment.invoice_amount as invoiceAmount,\n"
//            + "	if(inve_advance_vendor_payment.is_final_submit is true, 1, 0) as isFinalSubmit,\n"
//            + "	inve_advance_vendor_payment.`status`,"
//            + " CASE\n"
//            + "			\n"
//            + "			WHEN inve_advance_vendor_payment.`status` = 0 THEN\n"
//            + "			CONCAT( 'Submitted by ', jbp_roles.jbp_displayname ) \n"
//            + "			WHEN inve_advance_vendor_payment.`status` = 1 THEN\n"
//            + "			CONCAT( 'Approved by ', jbp_roles.jbp_displayname ) \n"
//            + "			WHEN inve_advance_vendor_payment.`status` = 2 THEN\n"
//            + "			CONCAT( 'Rejected by ', jbp_roles.jbp_displayname ) \n"
//            + "                 ELSE \n"
//            + "                 CONCAT( 'Forwarded by ', jbp_roles.jbp_displayname ) \n"
//            + "		END AS actionTaken 	 "
//            + "FROM\n"
//            + "	inve_advance_vendor_payment\n"
//            + "	INNER JOIN inve_purchase_committee ON inve_purchase_committee.pk = inve_advance_vendor_payment.inve_purchase_committee_pk\n"
//            + "	INNER JOIN department_master ON department_master.pk = inve_purchase_committee.department_master_pk\n"
//            + "	INNER JOIN employee_master ON employee_master.pk = inve_purchase_committee.buyer_employee_master_pk\n"
//            + "	INNER JOIN vendor_master ON vendor_master.pk = inve_advance_vendor_payment.vendor_master_pk\n"
//            + "	INNER JOIN finance_book_entity ON inve_purchase_committee.financial_entity_pk = finance_book_entity.pk\n"
//            + " LEFT JOIN jbp_roles ON jbp_roles.jbp_rid = inve_advance_vendor_payment.approval_role_pk "
//            + " WHERE\n"
//            + " inve_purchase_committee.department_master_pk IN ( SELECT inve_storekeeper_role_details.department_master_pk "
//            + " FROM inve_storekeeper_role INNER JOIN inve_storekeeper_role_details ON inve_storekeeper_role_details.inve_storekeeper_role_pk"
//            + " = inve_storekeeper_role.pk WHERE inve_storekeeper_role.employee_master_pk = #{userid} ) \n"
//            + " ${query1}\n"
//            + " ${query}\n"
//            + "	ORDER BY\n"
//            + "	inve_advance_vendor_payment.created_date DESC;";

    private static String s= "SELECT\n"
            +"workflow_code\n"
            +"FROM\n"
            +"inve_workflow_codes\n"
            +"WHERE\n"
            +"flag = 1 \n"
            +"AND type = 1;";
    public static void main(String[] args) {
        System.out.println(s);
    }
}
